### ISSUE TITLE
Project review

### ISSUE THREAD

**Issue by ariloc** [ariloc/mal-trending#1]

**Comment by JuanFrontons** [comment]
Feedback App RN Ariel: 
- Muy buena organización y estructura en general
- Buen uso de la navegación, componentes y lógica de React
- Tipado typescript bien utilizado, especifico y completo
- Los context generalmente se definen fuera de App.tsx https://github.com/ariloc/mal-ranking/blob/d6dc76eaeac2fba06e7ad1e9d1796f604fef0791/App.tsx#L22
- Lo unico que veo raro es el patron de repo Singleton en el context que expone los metodos de la api, me parece que con react query por como funciona no es necesario estar haciendo un context global para eso, es suficiente con hacer un hook que se encargue de manejar la logica de react query y exportarlo directamente para ser usado por los componentes, de esa manera lo unico que interactua con tu logica es el hook de react query que por dentro ya maneja tu data con un context y actualiza la query cuando sea necesario. Habria que ver si no conviene usar funciones exportadas sueltas y no el repo, pero creo que eso no esta mal, solo no sigue el "estilo" de arrow functions y hooks de react nada mas.

Seria una cosa así: 
```
export const useAnime = () => {
  const queryClient = useQueryClient();
  const malRepo: IMalRepository = new MalRepository()

  const getTrendingAnimeRanking = ({pageParam}) =>
    useInfiniteQuery({
        queryKey: ['trending-anime'],
        queryFn: ({ pageParam }) => malRepo.getAnimeRanking(pageParam),
        initialPageParam: 0,
        getNextPageParam: (lastPage, _) => lastPage.nextPage,
    });

return 
{
getTrendingAnimeRanking
}
}
```
Y después usas eso en tus componentes:

`
const {  data, isLoading, isLoadingError, fetchNextPage, refetch } = useAnime().getTrendingAnimeRanking; 
`

**Comment by ariloc** [comment]
Entendido, gracias por el feedback!

En cuanto a tus últimos dos puntos:

-  Veo lo que decís de declarar el context afuera de App.tsx. Lo había visto en muchos lugares como que se acostumbraba poner junto con la función `App()`, pero tenés razón que eso hace que importe App.tsx en las screens, lo que no es ideal. 
En ese sentido, creo que también sería mejor separar el `RootStackParamList`, puede ser? Eso me sirve para tipar los props de las screens con el navigation y los argumentos que les pueda pasar.
Ahora bien, **a la hora de separarlos, en dónde corresponderían los archivos en la estructura del proyecto?** Capaz el context podría dejarlo junto con el App.tsx, y se me ocurre que el `RootStackParamList` podría ir en _data_, pero capaz sabés mejor al respecto.

- Tenés razón que podría haberlo hecho en forma de hook o una función por separado, inclusive con la lógica sin necesidad del Repository. De hecho, por el tamaño del proyecto hasta podría justificarse usar funciones sueltas por separado e importarlas.
El motivo por el cual opté por un patrón más similar a Singleton con un Repository es que, por un lado, me resultaba raro tener funciones sueltas que no estén en una clase viniendo de Kotlin / Java. Observé que no era frecuente el uso de clases con React Native (o React en general), pero dada la opción con TypeScript creí que quedaba más organizado. Al respecto de eso, de hecho encontré ejemplos con el modelo de Repository que llegaban a definir una interfaz genérica, pero consideré que superaban al tamaño del proyecto y que no valía la pena implementarlos en este caso.
Por otro lado, teniendo ya el Repository, había primero pensado en directamente declararlo dentro de cada screen, pero no me convencía la idea de crear dos instancias separadas de una misma clase cuando se podría utilizar una sola. Así encontré que podía usar un context. **Según el ejemplo que presentás entiendo que debería hacer otro hook para la otra screen, no? En ese caso no tendría el mismo problema con estar declarando instancias separadas? O eso no es problema en React Native?
Además, cuál sería la diferencia a declararlo directamente en la screen? Sería sólamente para separar la lógica?**
Sino también podría directamente pensar en separar la lógica de cada screen y tratar cada caso por separado, pero no me parecía conveniente dado que el endpoint es el mismo, además de que uso la misma API key.

Y por último, como una pregunta / aclaración general del proyecto, habrás visto (dado que lo comentaste en el último punto) que seguí un diseño de código con `function`s comunes en vez de arrow functions. Esto es una duda que me surgió y que según pude encontrar, hacen lo mismo, a lo que usar una u otra se reduce a estilo del código.
Veía que en las guías más modernas de React Native se frecuentaba el uso de arrow functions, pero una vez más la costumbre hizo que me decante más a favor de las functions convencionales. Esto se debe, una vez más, por su similitud en estructura a lenguajes como Kotlin o Java con los que estoy más acostumbrado.
También no estaba del todo seguro si la sintaxis utilizada en las guías era o no algo enfocado a principiantes que en "production code" deba ser muy utilizado. En ese sentido, mi pregunta sería, **debería preferir de ahora en adelante por un estilo de código en React Native más orientado a arrow functions? Son realmente las más frecuentadas?
Y para cerrar, el patrón con Service y Repository es común que se utilice? O debería preferir hooks como en tu ejemplo?**

**Comment by andres-pasquinelli** [comment]
Hola Ariel!! como vas? Con respecto a las `function` y arrow función es casi lo mismo pero hay un par de cosa a tener en cuenta. Te dejo un par de link para mirrar al respecto:

(esta web para todo lo que es javascript para mi la rompe, esta muy buena)
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions

https://www.freecodecamp.org/news/the-difference-between-arrow-functions-and-normal-functions/

**Comment by JuanFrontons** [comment]
> Entendido, gracias por el feedback!
> 
> En cuanto a tus últimos dos puntos:
> 
> * Veo lo que decís de declarar el context afuera de App.tsx. Lo había visto en muchos lugares como que se acostumbraba poner junto con la función `App()`, pero tenés razón que eso hace que importe App.tsx en las screens, lo que no es ideal.
>   En ese sentido, creo que también sería mejor separar el `RootStackParamList`, puede ser? Eso me sirve para tipar los props de las screens con el navigation y los argumentos que les pueda pasar.
>   Ahora bien, **a la hora de separarlos, en dónde corresponderían los archivos en la estructura del proyecto?** Capaz el context podría dejarlo junto con el App.tsx, y se me ocurre que el `RootStackParamList` podría ir en _data_, pero capaz sabés mejor al respecto.


Si, para los context podes hacer un `contexts/malRepoContext.tsx`. Y el param de navigation podria ir en `data/navigation.ts` por ejemplo o hacer un `navigation/types.ts` o un `types.ts` suelto segun el tamaño tambien yo creo.


> * Tenés razón que podría haberlo hecho en forma de hook o una función por separado, inclusive con la lógica sin necesidad del Repository. De hecho, por el tamaño del proyecto hasta podría justificarse usar funciones sueltas por separado e importarlas.
>   El motivo por el cual opté por un patrón más similar a Singleton con un Repository es que, por un lado, me resultaba raro tener funciones sueltas que no estén en una clase viniendo de Kotlin / Java. Observé que no era frecuente el uso de clases con React Native (o React en general), pero dada la opción con TypeScript creí que quedaba más organizado. Al respecto de eso, de hecho encontré ejemplos con el modelo de Repository que llegaban a definir una interfaz genérica, pero consideré que superaban al tamaño del proyecto y que no valía la pena implementarlos en este caso.


Claro si no esta mal, lo que lo hace raro es el uso del context mas que nada creo yo, que es obligatorio en este caso digamos para el Singleton.


>   Por otro lado, teniendo ya el Repository, había primero pensado en directamente declararlo dentro de cada screen, pero no me convencía la idea de crear dos instancias separadas de una misma clase cuando se podría utilizar una sola. Así encontré que podía usar un context. **Según el ejemplo que presentás entiendo que debería hacer otro hook para la otra screen, no? En ese caso no tendría el mismo problema con estar declarando instancias separadas? O eso no es problema en React Native?


Claro tendrias dos instancias diferentes, justo lo que puse arriba ^. La otra screen usaria el mismo hook pero llamaria a otra funcion, igualmente tambien tendrias dos instancias del repo porque si llamas al hook en diferentes componentes se crearia otra instancia por mas que sea el mismo hook. De ahi que como que no combina usar clases y hooks, hacer funciones sueltas y exportarlas tiene mas sentido.


>   Además, cuál sería la diferencia a declararlo directamente en la screen? Sería sólamente para separar la lógica?**
>   Sino también podría directamente pensar en separar la lógica de cada screen y tratar cada caso por separado, pero no me parecía conveniente dado que el endpoint es el mismo, además de que uso la misma API key.


Si separaria la logica pero tambien tendrias un hook que maneje toda la logica de react query referida a todo lo que sea 'anime' que se usaria en las dos screens y solo eso manejaria tus funciones del service directamente.


> 
> Y por último, como una pregunta / aclaración general del proyecto, habrás visto (dado que lo comentaste en el último punto) que seguí un diseño de código con `function`s comunes en vez de arrow functions. Esto es una duda que me surgió y que según pude encontrar, hacen lo mismo, a lo que usar una u otra se reduce a estilo del código. Veía que en las guías más modernas de React Native se frecuentaba el uso de arrow functions, pero una vez más la costumbre hizo que me decante más a favor de las functions convencionales. Esto se debe, una vez más, por su similitud en estructura a lenguajes como Kotlin o Java con los que estoy más acostumbrado. También no estaba del todo seguro si la sintaxis utilizada en las guías era o no algo enfocado a principiantes que en "production code" deba ser muy utilizado. En ese sentido, mi pregunta sería, **debería preferir de ahora en adelante por un estilo de código en React Native más orientado a arrow functions? Son realmente las más frecuentadas? Y para cerrar, el patrón con Service y Repository es común que se utilice? O debería preferir hooks como en tu ejemplo?**

Bueno acá @andres-pasquinelli ya te respondió jajaj, no cambia mucho, si es por costumbre esta bien, mírate ahi las diferencias, pero si son detalles muy minuciosos.
El patron no lo suelo ver mucho, no se @andres-pasquinelli si tiene idea, pero seguro que es algo eficiente de hacer, capaz en cosas mas grandes? Seguro que se puede tranquilamente como en cualquier lenguaje.

Igual son todos detalles muy específicos y de costumbre como vos decís así que tranqui, en general el proyecto esta impecable! 👌 💯
